version = "Two"
edition = "2018"
unstable_features = true

enum_discrim_align_threshold = 20
fn_single_line = true
format_code_in_doc_comments = true
max_width = 100
merge_imports = true
newline_style = "Unix"
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
wrap_comments = true
